### PR TITLE
preserve: Support regular expressions

### PR DESCRIPTION
**Pull request by awelzel**
Hello,

this is a RFC for a new keyword `@preserveprefix` that preserves multiple chains that start with a given prefix. This can be used in environments where another tool creates dynamic chains (e.g. `KUBE-SVC-*`) that should all be preserved, but are not named predictably.

This might a bit of an exotic case. The keyword processing is also unusual in that existing rules are queried during processing of a keyword, but it seems to work..

Is this something that could be interesting to include? Any other thoughts on this?

Thanks,
   Arne

PS: Initially the idea was to have a `@preserveglob`, but my Perl knowledge is limited and there didn't seem to be a straightforward way without including additional modules / converting glob to regex, etc.

### CODE REVIEW

**Comment by retr0h** [comment]
This is a great solution, especially for those of us running ferm and wanting to use kubernetes, thanks @awelzel !

**Comment by MaxKellermann** [comment]
I've never used Kubernetes, but it sounds like a good idea to give users a way to preserve a dynamic set of chains, if it helps to coexist with Kubernetes and similar programs.

> The keyword processing is also unusual in that existing rules are queried during processing of a keyword, but it seems to work..

I don't like that part, and I don't like how you implemented it. This dumps all rules in human-readable format, parses the human-readable output, and later ferm needs to dump all rules again to copy those preserved chains. That's not only unnecessary overhead, but also very fragile, because human-readable text can change any time. For example it will break if tools decide to change wording or if they print i18n text.

I rather suggest collecting all expressions for preserved dynamic chains, and later after parsing the `iptables-save` output (which goes to `$chain_info->{preserve}`) you can check all expressions against the list of chains parsed from there. That way, you use the already existing and stable `iptables-save` parser, and it's invoked only once.

> PS: Initially the idea was to have a `@preserveglob`, but my Perl knowledge is limited and there didn't seem to be a straightforward way without including additional modules / converting glob to regex, etc.

What about exposing regular expressions to ferm users? Maybe even:
```
@preserve "/^a regular expression/"
```
So, without a new keyword - if the name begins and ends with a slash, ferm assumes it's a RE.

**Comment by awelzel** [comment]
> 
> I don't like that part, and I don't like how you implemented it. This dumps all rules in human-readable format, parses the human-readable output, and later ferm needs to dump all rules again to copy those preserved chains. That's not only unnecessary overhead, but also very fragile, because human-readable text can change any time. For example it will break if tools decide to change wording or if they print i18n text.

Great points. Thanks for the feedback, very much appreciated. Also ran into an issue while testing where two `@preserveprefix` invocations would result in an inconsistent snapshot of chains. So yeah, that all was very brittle and your points are spot on.

> 
> I rather suggest collecting all expressions for preserved dynamic chains, and later after parsing the `iptables-save` output (which goes to `$chain_info->{preserve}`) you can check all expressions against the list of chains parsed from there. That way, you use the already existing and stable `iptables-save` parser, and it's invoked only once.

So I've attempted this, but still setting `$chain_info->${preserve}=1` as an intermediate step which is later then later replaced with the actual code in `rules_to_save()`.

I think the code got better / simpler, but maybe it's not quite what you had in mind. Let me know.

> 
> What about exposing regular expressions to ferm users? Maybe even:
> 
> ```
> @preserve "/^a regular expression/"
> ```
> 
> So, without a new keyword - if the name begins and ends with a slash, ferm assumes it's a RE.

I've did that now too. Technically it seems one can create chains that start and end with a `/` so this might be a breaking change. But maybe not an issue in practice.

I've added one extra commits with a few tests, though couldn't quite fit them in the current tests. If you would consider merging, I'll drop that commit first.

**Comment by awelzel** [comment]
> I've added one extra commits with a few tests, though couldn't quite fit them in the current tests. If you would consider merging, I'll drop that commit first.

I've attempted to make them fit providing an explicit target for these which uses `unshare` tricks to execute in a new network namespace. Force pushed the current state.

**Comment by MaxKellermann** [comment]
I bow before your namespace magic, very cool!
The problem is that it's fragile; my main computer doesn't have iptables support; iptables isn't even installed (yes that's the computer I develop ferm on). So I had to remove your hack, and replaced it with a mocking feature, where you can inject the previous ruleset from a file instead of calling iptables-save. This isn't as cool as using network namespaces, but should work everywhere, less complexity.

**Pull request merged**
